name: watch_it
description: The simple state management powered by get_it. It allows to observe changes of objects inside the get_it service locator and rebuild the UI accordingly.
version: 1.6.5
homepage: https://github.com/escamoteur/watch_it
funding:
  - https://github.com/sponsors/escamoteur/

environment:
  sdk: '>=2.19.6 <4.0.0'
  flutter: ">=3.0.0"

topics:
  - state-management
  - dependency-injection
  - architecture
  - get-it

dependencies:
  get_it: ^8.0.0
  flutter:
    sdk: flutter
  functional_listener: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
